icons_format = "{icon}"

[theme]
theme = "solarized-dark"
[theme.overrides]
idle_bg = "#123456"
idle_fg = "#abcdef"

[icons]
icons = "awesome4"
[icons.overrides]
bat = ["|E|", "|_|", "|=|", "|F|"]
bat_charging = "|^| "

[[block]]
block = "battery"
format = " $icon $percentage "

[[block]]
block = "cpu"
info_cpu = 20
warning_cpu = 50
critical_cpu = 90

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = "data: $available.eng(w:2) "

[[block]]
block = "memory"
format = " $icon  $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "backlight"
device = "amdgpu_bl1"
format = "$icon $brightness "
# Remvoe block click action
[[block.click]]
button = "left"
cmd = ""

[[block]]
block = "sound"
driver = "pulseaudio"
format = " $icon  $volume "
show_volume_when_muted = true
[block.theme_overrides]
warning_bg = "#123456"
warning_fg = "#abcdef"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %m/%d %R') "
